/** @file Arguments.hpp
	Contains macros for parsing coroutine arguments. */
#ifndef __libcr_pp_arguments_hpp_defined
#define __libcr_pp_arguments_hpp_defined

// Arguments

#include "../util/RefConv.hpp"
#include "../util/Argument.hpp"

#define LIBCR_HELPER_IGNORE(...)
#define LIBCR_HELPER_IGNORE2(...)
#define LIBCR_HELPER_ARGUMENT_NAME(...) LIBCR_HELPER_IGNORE2 __VA_ARGS__
#define LIBCR_HELPER_IGNORE_AFTER(...) __VA_ARGS__ LIBCR_HELPER_IGNORE(
#define LIBCR_HELPER_ARGUMENT_TYPE(...) LIBCR_HELPER_IGNORE_AFTER __VA_ARGS__ )

#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES(...) LIBCR_HELPER_OVERLOADP(LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES, __VA_ARGS__)

#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES0()
#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES1(arg) \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLE(arg);
#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES2(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLE(arg1); \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES1(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES3(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLE(arg1); \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES2(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES4(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLE(arg1); \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES3(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES5(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLE(arg1); \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES4(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES6(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLE(arg1); \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES5(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES7(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLE(arg1); \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES6(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_VARIABLE(arg) \
	cr::util::ref_conv_t< \
		LIBCR_HELPER_ARGUMENT_TYPE(arg)> \
		LIBCR_HELPER_ARGUMENT_NAME(arg)

#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS0() void
#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS1(arg1) \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETER(arg1)
#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS2(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETER(arg1), \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS1(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS3(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETER(arg1), \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS2(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS4(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETER(arg1), \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS3(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS5(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETER(arg1), \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS4(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS6(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETER(arg1), \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS5(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS7(arg1, ...) \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETER(arg1), \
	LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS6(__VA_ARGS__)
#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETER(arg) \
	LIBCR_HELPER_ARGUMENT_TYPE(arg) LIBCR_HELPER_ARGUMENT_NAME(arg)

#define LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS(...) \
	LIBCR_HELPER_OVERLOADP( \
		LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS, \
		__VA_ARGS__)

#define LIBCR_HELPER_CREATE_PREPARE(...) \
	void cr_prepare( \
		LIBCR_HELPER_CREATE_ARGUMENT_PARAMETERS(__VA_ARGS__)) \
	{ \
		LIBCR_HELPER_ASSIGN_ARGUMENTS(__VA_ARGS__) \
	} \
	LIBCR_HELPER_CREATE_ARGUMENT_VARIABLES(__VA_ARGS__)

#define LIBCR_HELPER_ASSIGN_ARGUMENTS(...) \
	LIBCR_HELPER_OVERLOADP( \
		LIBCR_HELPER_ASSIGN_ARGUMENTS, \
		__VA_ARGS__)
#define LIBCR_HELPER_ASSIGN_ARGUMENT(arg) \
	cr::util::assign(\
		this->LIBCR_HELPER_ARGUMENT_NAME(arg), \
		std::forward<LIBCR_HELPER_ARGUMENT_TYPE(arg)>(LIBCR_HELPER_ARGUMENT_NAME(arg)));
#define LIBCR_HELPER_ASSIGN_ARGUMENTS0()
#define LIBCR_HELPER_ASSIGN_ARGUMENTS1(arg1) \
	LIBCR_HELPER_ASSIGN_ARGUMENT(arg1)
#define LIBCR_HELPER_ASSIGN_ARGUMENTS2(arg1, ...) \
	LIBCR_HELPER_ASSIGN_ARGUMENT(arg1) \
	LIBCR_HELPER_ASSIGN_ARGUMENTS1(__VA_ARGS__)
#define LIBCR_HELPER_ASSIGN_ARGUMENTS3(arg1, ...) \
	LIBCR_HELPER_ASSIGN_ARGUMENT(arg1) \
	LIBCR_HELPER_ASSIGN_ARGUMENTS2(__VA_ARGS__)
#define LIBCR_HELPER_ASSIGN_ARGUMENTS4(arg1, ...) \
	LIBCR_HELPER_ASSIGN_ARGUMENT(arg1) \
	LIBCR_HELPER_ASSIGN_ARGUMENTS3(__VA_ARGS__)
#define LIBCR_HELPER_ASSIGN_ARGUMENTS5(arg1, ...) \
	LIBCR_HELPER_ASSIGN_ARGUMENT(arg1) \
	LIBCR_HELPER_ASSIGN_ARGUMENTS4(__VA_ARGS__)
#define LIBCR_HELPER_ASSIGN_ARGUMENTS6(arg1, ...) \
	LIBCR_HELPER_ASSIGN_ARGUMENT(arg1) \
	LIBCR_HELPER_ASSIGN_ARGUMENTS5(__VA_ARGS__)
#define LIBCR_HELPER_ASSIGN_ARGUMENTS7(arg1, ...) \
	LIBCR_HELPER_ASSIGN_ARGUMENT(arg1) \
	LIBCR_HELPER_ASSIGN_ARGUMENTS6(__VA_ARGS__)

#endif