/** @file Overload.hpp
	Contains macros that enable dynamic overloading of macros. */
#ifndef __libcr_pp_overload_hpp_defined
#define __libcr_pp_overload_hpp_defined

// OVERLOAD

#define LIBCR_HELPER_OVERLOAD_CAT(a,b) a##b
#define LIBCR_HELPER_OVERLOAD_BIND(f, args) f args
#define LIBCR_HELPER_OVERLOAD_BIND2(f, args) f args

#define LIBCR_HELPER_OVERLOAD_ZEROPAD_IF_EMPTY2(...) \
	LIBCR_HELPER_OVERLOAD_ZEROPAD_IF_EMPTY2_ ## __VA_ARGS__
#define LIBCR_HELPER_OVERLOAD_ZEROPAD_IF_EMPTY2_ \
	0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0

#define LIBCR_HELPER_OVERLOAD_ARGC_HELPER2(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, count, ...) count
#define LIBCR_HELPER_OVERLOAD_ARGC_HELPER1(args) \
	LIBCR_HELPER_OVERLOAD_ARGC_HELPER2 args
#define LIBCR_HELPER_OVERLOAD_ARGC(...) \
	LIBCR_HELPER_OVERLOAD_ARGC_HELPER1((\
		LIBCR_HELPER_OVERLOAD_ZEROPAD_IF_EMPTY2(__VA_ARGS__), \
		16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0))
#define LIBCR_HELPER_OVERLOAD(base, ...) \
	LIBCR_HELPER_OVERLOAD_BIND2(\
		LIBCR_HELPER_OVERLOAD_GET_NAME(\
			base, \
			LIBCR_HELPER_OVERLOAD_ARGC(__VA_ARGS__)), \
		(__VA_ARGS__))
#define LIBCR_HELPER_OVERLOAD_GET_NAME(base, argc) \
	LIBCR_HELPER_OVERLOAD_BIND(\
		LIBCR_HELPER_OVERLOAD_CAT, \
		(base, argc))

// OVERLOADP

#define LIBCR_HELPER_OVERLOADP_ZEROPAD_IF_EMPTY2(...) \
	__VA_ARGS__ ## LIBCR_HELPER_OVERLOAD_ZEROPAD_IF_EMPTY2_
#define LIBCR_HELPER_OVERLOADP_ARGC(...) \
	LIBCR_HELPER_OVERLOAD_ARGC_HELPER1((\
		LIBCR_HELPER_OVERLOADP_ZEROPAD_IF_EMPTY2(__VA_ARGS__), \
		16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0))

#define LIBCR_HELPER_OVERLOADP(base, ...) \
	LIBCR_HELPER_OVERLOAD_BIND2(\
		LIBCR_HELPER_OVERLOAD_GET_NAME(\
			base, \
			LIBCR_HELPER_OVERLOADP_ARGC(__VA_ARGS__)), \
		(__VA_ARGS__))


// OVERLOAD_EXISTS

#define LIBCR_HELPER_BIND3(f, args) f args
#define LIBCR_HELPER_BIND4(f, args) f args
#define LIBCR_HELPER_ZEROPAD_IF_EMPTY(...) LIBCR_HELPER_ZEROPAD_IF_EMPTY_ ## __VA_ARGS__
#define LIBCR_HELPER_ZEROPAD_IF_EMPTY_ 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0
#define LIBCR_HELPER_EXISTS_HELPER(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,count,...) count
#define LIBCR_HELPER_MAKE_LIST(...) (__VA_ARGS__)
#define LIBCR_HELPER_EXISTS(...) LIBCR_HELPER_BIND4( \
		LIBCR_HELPER_EXISTS_HELPER, \
		(LIBCR_HELPER_ZEROPAD_IF_EMPTY(__VA_ARGS__),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1))

#define LIBCR_HELPER_OVERLOAD_EXISTS(base, ...) \
	LIBCR_HELPER_BIND3( \
		LIBCR_HELPER_OVERLOAD_EXISTS_GET_NAME( \
			(base, \
			LIBCR_HELPER_EXISTS(__VA_ARGS__))), \
		(__VA_ARGS__))

#define LIBCR_HELPER_OVERLOAD_EXISTS_GET_NAME(args) LIBCR_HELPER_OVERLOAD_EXISTS_GET_NAME_HELPER args
#define LIBCR_HELPER_OVERLOAD_EXISTS_GET_NAME_HELPER(base, exists) base##exists

#endif